/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Coffee: typeof import('./src/components/Coffee.vue')['default']
    Cooffee: typeof import('./src/components/Cooffee.vue')['default']
    InstallAppModal: typeof import('./src/components/common/InstallAppModal.vue')['default']
    MPop: typeof import('./src/components/common/MPop.vue')['default']
    MusicList: typeof import('./src/components/MusicList.vue')['default']
    MvPlayer: typeof import('./src/components/MvPlayer.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NPopover: typeof import('naive-ui')['NPopover']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSlider: typeof import('naive-ui')['NSlider']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTooltip: typeof import('naive-ui')['NTooltip']
    NVirtualList: typeof import('naive-ui')['NVirtualList']
    PlayBottom: typeof import('./src/components/common/PlayBottom.vue')['default']
    PlayListsItem: typeof import('./src/components/common/PlayListsItem.vue')['default']
    PlaylistType: typeof import('./src/components/PlaylistType.vue')['default']
    PlayVideo: typeof import('./src/components/common/PlayVideo.vue')['default']
    RecommendAlbum: typeof import('./src/components/RecommendAlbum.vue')['default']
    RecommendSinger: typeof import('./src/components/RecommendSinger.vue')['default']
    RecommendSonglist: typeof import('./src/components/RecommendSonglist.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchItem: typeof import('./src/components/common/SearchItem.vue')['default']
    SongItem: typeof import('./src/components/common/SongItem.vue')['default']
  }
}
